### ISSUE TITLE
Error on search: TypeError: Cannot read property 'defaultOperator' of undefined

### ISSUE THREAD

**Issue by synox** [sematext/logsene-cli#4]
Login works, but then search does not: 

	{ ~ }  » logsene search                                                                       ~ 1
	TypeError: Cannot read property 'defaultOperator' of undefined
	    at _getQuery (D:\dev\apps\node\node_modules\logsene-cli\commands\search.js:344:44)
	    at _run [as run] (D:\dev\apps\node\node_modules\logsene-cli\commands\search.js:47:44)
	    at D:\dev\apps\node\node_modules\logsene-cli\node_modules\ronin\build\command.js:260:9
	    at iterate (D:\dev\apps\node\node_modules\logsene-cli\node_modules\ronin\node_modules\async\lib\async.js:146:13)
	    at null._onTimeout (D:\dev\apps\node\node_modules\logsene-cli\node_modules\ronin\node_modules\async\lib\async.js:157:25)
	    at tryOnTimeout (timers.js:224:11)
	    at Timer.listOnTimeout (timers.js:198:5)

1.4.2 installed over npm on windows 7.

**Comment by otisg** [comment]
Does it work for any query?  What happens if you run queries like:

- foo
- "foo bar"
- foo AND bar
- foo OR bar
- +foo -bar

**Comment by megastef** [comment]
logsene-cli gets this error with an empty query. It would be better to use "*" for search or output an error message about the missing query. 

`logsene search *` works for me.

**Comment by otisg** [comment]
Works for you now, @synox ?

**Comment by synox** [comment]
I have the same Problem with any query.

**Comment by megastef** [comment]
We just released 1.4.4 could you please run first:
```
sudo npm i -g  logsene-cli@1.4.4
```

**Comment by megastef** [comment]
Oh, sorry you use windows and there is no sudo: 

```
npm i -g  logsene-cli@1.4.4
```

**Comment by synox** [comment]
bravo, it works with 1.4.4.
